# Generated by Django 4.2.5 on 2023-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_cart_options_remove_cart_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ManyToManyField(related_name='cart_items', to='menu.cart', verbose_name='Корзина'),
        ),
    ]
